#!/bin/sh

dry_run=0
fuzz_seconds=

while getopts "hnV:" opt; do
    case "$opt" in
        h)
            cat <<EOF 1>&2
Usage: $0 [-hn] [number_of_fuzzers]

Parameters:
    -h  Show help
    -n  Dry run; echo commands instead of running them
EOF
            exit 0
            ;;
        n) dry_run=1;;
        V) fuzz_seconds="$OPTARG"
    esac
done

shift $(( $OPTIND - 1 ))

command() {
    if [ "$dry_run" -eq 1 ]; then
        echo "$@"
    else
        "$@"
        res=$?
        if [ $res -ne 0 ]; then
            echo "Command returned $res: $@"
            exit $res
        fi
    fi
}

if [ ! -e in ]; then
    echo "generating input files using ffmpeg..." 1>&2
    if [ -e in~ ]; then
        echo "removing scratch directory 'in~':" 1>&2
        command rm -ir in~
    fi
    command mkdir in~
    command ffmpeg -f lavfi -i smptebars -frames:v 30 in~/ffmpeg-smptebars-30f.mp4
    command ffmpeg -f lavfi -i color=color=black -frames:v 1 in~/ffmpeg-black-1f.mp4
    command mv -n in~ in
fi

command cargo afl build

FUZZ_ARGS=
if [ -n "$fuzz_seconds" ]; then
    FUZZ_ARGS="$FUZZ_ARGS -V $fuzz_seconds"
fi

if [ -n "$1" ]; then
    for idx in $(seq 1 $idx); do
        command cargo afl fuzz ${FUZZ_ARGS} -i in -o out -S fuzzer-$idx ../target/debug/mp4san-fuzz &
    done
fi

command cargo afl fuzz ${FUZZ_ARGS} -i in -o out -M main ../target/debug/mp4san-fuzz
