[package]
name = "mediasan-common-test"
edition = "2021"
version = "0.1.0"

publish = false

[dependencies]
env_logger = { workspace = true }
libflate = { workspace = true }
log = { workspace = true }
