[package]
name = "webpsan-test"
edition.workspace = true
version.workspace = true

publish = false

[features]
default = []
libwebp = ["dep:libwebp-sys"]

[dependencies]
libwebp-sys = { workspace = true, optional = true }
log = { workspace = true }
thiserror = { workspace = true }
